# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cluster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine',
            new_name='Course',
        ),
    ]
